services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static:/app/static
      - media:/app/media
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DEBUG=1
      - CSRF_TRUSTED_ORIGINS=http://localhost:8000
      - DJANGO_SECRET_KEY=django-insecure-development-key-for-testing-only
      - API_KEYS="api-key-1,api-key-2,dev-api-key-for-testing"
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ["/app/entrypoint.sh"]
    env_file:
      - APPCONFIG.env
      - .env

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  static:
  media: 
