# Generated by Django 4.2.27 on 2026-01-28 01:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Collection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Name of the collection", max_length=200
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "date",
                    models.DateField(
                        blank=True,
                        help_text="Primary date of the collection",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "name"],
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the event", max_length=200),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("race", "Race"),
                            ("cruise", "Cruise"),
                            ("delivery", "Delivery"),
                            ("training", "Training"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("date", models.DateField(help_text="Date of the event")),
                (
                    "event_number",
                    models.PositiveIntegerField(
                        blank=True, help_text="Event number in collection", null=True
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "collection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="tracks.collection",
                    ),
                ),
            ],
            options={
                "ordering": ["date", "event_number"],
            },
        ),
        migrations.CreateModel(
            name="Vessel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of the vessel", max_length=200),
                ),
                (
                    "sail_number",
                    models.CharField(
                        blank=True, help_text="Sail number", max_length=50, null=True
                    ),
                ),
                (
                    "model_info",
                    models.CharField(
                        blank=True,
                        help_text="Vessel model/type",
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    "mmsi",
                    models.CharField(
                        blank=True,
                        help_text="MMSI for AIS tracking",
                        max_length=9,
                        null=True,
                    ),
                ),
                (
                    "aliases",
                    models.JSONField(
                        default=list, help_text="Alternative names for this vessel"
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True,
                        help_text="96x96 pixel icon for this vessel",
                        null=True,
                        upload_to="vessel_icons/",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Recording",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Optional name for this recording",
                        max_length=200,
                    ),
                ),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "bounding_box",
                    models.JSONField(
                        blank=True,
                        help_text='{"min_lat": x, "max_lat": x, "min_lon": x, "max_lon": x}',
                        null=True,
                    ),
                ),
                ("point_count", models.PositiveIntegerField(default=0)),
                (
                    "distance_nm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total distance in nautical miles",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "s3_prefix",
                    models.CharField(
                        blank=True,
                        help_text="S3 prefix for track files (e.g., 'tracks/uuid/')",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="processing",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("private", "Private"),
                            ("shared", "Shared"),
                            ("public", "Public"),
                        ],
                        default="private",
                        max_length=20,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recordings",
                        to="tracks.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="User who uploaded this recording",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vessel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recordings",
                        to="tracks.vessel",
                    ),
                ),
            ],
            options={
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="VesselPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_primary_owner", models.BooleanField(default=False)),
                ("can_upload_tracks", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Approval"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("suspended", "Suspended"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vessel_permissions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vessel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_permissions",
                        to="tracks.vessel",
                    ),
                ),
            ],
            options={
                "ordering": ["user", "vessel"],
                "unique_together": {("user", "vessel")},
            },
        ),
    ]
