# Generated by Django 4.2.27 on 2026-01-28 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tracks", "0002_add_event_share_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="recording",
            name="crop_end_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp where crop ended (if cropped from end)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recording",
            name="crop_start_time",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp where crop started (if cropped from beginning)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="recording",
            name="is_cropped",
            field=models.BooleanField(
                default=False, help_text="Quick flag to identify cropped recordings"
            ),
        ),
        migrations.AddField(
            model_name="recording",
            name="original_recording",
            field=models.ForeignKey(
                blank=True,
                help_text="The recording this was cropped from (if any)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cropped_versions",
                to="tracks.recording",
            ),
        ),
    ]
