name: Deploy to AWS App Runner

on:
  push:
    branches: [ main, staging ]
  workflow_dispatch:

env:
  AWS_REGION: ${{ secrets.AWS_REGION || 'us-east-1' }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Read APPCONFIG.env and set APP_NAME
        id: appconfig
        run: |
          BASE_APP_NAME=$(grep '^APP_NAME=' APPCONFIG.env | cut -d '=' -f2)
          if [ "$GITHUB_REF" = "refs/heads/staging" ]; then
            APP_NAME="${BASE_APP_NAME}_staging"
          else
            APP_NAME="${BASE_APP_NAME}"
          fi
          echo "APP_NAME=$APP_NAME" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          if [ -f "cdk/requirements.txt" ]; then
            pip install -r cdk/requirements.txt
          fi

      - name: List available secrets in AWS Secrets Manager
        run: |
          echo "Checking for secrets in AWS Secrets Manager for app: ${{ env.APP_NAME }}"
          SECRETS=$(aws secretsmanager list-secrets --filters Key=name,Values="${{ env.APP_NAME }}_" --query "SecretList[].Name" --output text)
          if [ -z "$SECRETS" ]; then
            echo "⚠️ No secrets found matching pattern: ${{ env.APP_NAME }}_*"
            echo "Make sure to push secrets using ./cdk/push_secrets.py before deployment"
          else
            echo "✅ Found the following secrets:"
            echo "$SECRETS" | tr '\t' '\n' | while read SECRET; do
              KEYS=$(aws secretsmanager get-secret-value --secret-id "$SECRET" --query "SecretString" --output text | jq -r 'keys | join(", ")')
              echo "  - $SECRET (Keys: $KEYS)"
            done
          fi

      - name: Make deploy script executable
        run: chmod +x scripts/deploy.sh

      - name: Run deployment with verbose logging
        run: |
          export APP_NAME=${{ env.APP_NAME }}
          export AWS_REGION=${{ env.AWS_REGION }}
          export CDK_DEBUG=true  # Enable CDK debug logging
          export CDK_LOG_LEVEL=debug  # Set CDK log level to debug
          ./scripts/deploy.sh 